version: '3'

services:
  rust:
    build:
      context: ./container/rust
      dockerfile: Dockerfile
    
    container_name: rust
    tty: true

    volumes:
      - ./src:/root/workspace
    
    environment:
      - USER=user